[build.targets.wheel]
only-include = ["src/pydra/tasks/templateflow"]
sources = ["src"]

[envs.default]
dependencies = [
  "pytest",
]
[envs.default.scripts]
test = "pytest {args:.}"

[[envs.all.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black",
  "isort",
]
[envs.lint.scripts]
all = [
  "black --check --diff {args:.}",
  "isort --check --diff {args:.}",
]
fix = [
  "black --quiet {args:.}",
  "isort --quiet {args:.}",
]
